version: '3.8'

services:
  db:
    image: postgres:14
    container_name: postgres-mardi
    environment:
      POSTGRES_DB: mardi
      POSTGRES_USER: mini
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - spring-net

  app:
    build: .
    container_name: spring-mardi
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - spring-net
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/mardi
      SPRING_DATASOURCE_USERNAME: mini
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_JPA_HIBERNATE_DDL_AUTO: create-drop

volumes:
  pgdata:

networks:
  spring-net:
